package com.example.anidb.utils.entry

const val ANIME = "data"
const val ID = "mal_id"
const val TITLE = "title"
const val IMAGE = "images"
const val IMAGE_TYPE = "jpg"
const val IMAGE_SIZE = "large_image_url"
const val DESCRIPTION = "synopsis"
const val STATUS = "status"
const val AIRED = "aired"
const val AIRED_TO = "to"
const val AIRED_FROM = "from"
const val MEMBERS = "members"
const val SCORE = "score"
const val RANK = "rank"
const val POPULARITY = "popularity"
const val FAVORITES = "favorites"
const val DURATION = "duration"
const val SEASON = "season"
const val EPISODES = "episodes"
const val GENRES = "genres"
const val STUDIOS = "studios"
